# IT309 - A3 transaction input stream used to create and maintain a linked list
A3trans = ('A,Washington',
           'A,Adams',
           'A,Jefferson',
           'A,Madison',
           'A,Monroe',
           'A,Quincy Adams',
           'A,Jackson',
           'A,Van Buren',
           'A,Harrison',
           'A,Tyler',
           'A,Polk',
           'A,Taylor',
           'A,Fillmore',
           'A,Pierce',
           'A,Buchanan',
           'A,Lincoln',
           'A,AJohnson',
           'A,Grant',
           'A,Hayes',
           'A,Garfield',
           'A,Arthur',
           'A,Cleveland',
           'A,Harrison',
           'A,Cleveland',
           'A,McKinley',
           'A,TRoosevelt',
           'IE,Wilson,A,TRoosevelt',
           'IE,Taft,B,Wilson',
           'A,Coolidge',
           'R',
           'R',
           'R',
           'A,Harding',
           'IE,Wilson,B,Harding',
           'A,Coolidge',
           'A,FDRoosevelt',
           'IE,Hoover,B,FDRoosevelt',
           'IA,2,Shuman',
           'IA,40,Kennedy',
           'A,LBJohnson',
           'IE,Nixon,A,LBJohnson',
           'IE,Eisenhower,B,Kennedy',
           'IE,Truman,B,Eisenhower')
           
